variables:
  DOCKER_REGISTRY: docker.io
  DOCKER_IMAGE: yuiweq1999/my_new_project  #  DockerHub 用戶名
  DOCKER_TAG: latest # 可以另外依照規則提供

stages:
  - build
  - test
  - deploy

build_image:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
  before_script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin $DOCKER_REGISTRY
  script:
    # 編譯專案並生成 JAR 檔案
    - ./mvnw clean package -DskipTests
    # build image
    - docker build -t $DOCKER_IMAGE:$DOCKER_TAG .
    - docker push $DOCKER_IMAGE:$DOCKER_TAG
  rules:
    - if: $CI_COMMIT_BRANCH == "main"